/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CandidaturasRouteImport } from './routes/candidaturas'
import { Route as ConquistasRouteImport } from './routes/conquistas'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ExtensaoRouteImport } from './routes/extensao'
import { Route as GameRouteImport } from './routes/game'
import { Route as GuiaAtsRouteImport } from './routes/guia-ats'
import { Route as IaRouteImport } from './routes/ia'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as RadarRouteImport } from './routes/radar'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as AIdRouteImport } from './routes/a.$id'
import { Route as EntrevistaIdRouteImport } from './routes/entrevista.$id'
import { Route as ApiPublicVagaMatchRouteImport } from './routes/api/public/vaga-match'
import { Route as ApiPublicExtensaoPerfilRouteImport } from './routes/api/public/extensao/perfil'
import { Route as ApiPublicExtensaoSalvarRouteImport } from './routes/api/public/extensao/salvar'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicRadarAlertasRouteImport } from './routes/api/public/radar/alertas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidaturasRoute = CandidaturasRouteImport.update({
  id: '/candidaturas',
  path: '/candidaturas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConquistasRoute = ConquistasRouteImport.update({
  id: '/conquistas',
  path: '/conquistas',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensaoRoute = ExtensaoRouteImport.update({
  id: '/extensao',
  path: '/extensao',
  getParentRoute: () => rootRouteImport,
} as any)
const GameRoute = GameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaAtsRoute = GuiaAtsRouteImport.update({
  id: '/guia-ats',
  path: '/guia-ats',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const RadarRoute = RadarRouteImport.update({
  id: '/radar',
  path: '/radar',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const AIdRoute = AIdRouteImport.update({
  id: '/a/$id',
  path: '/a/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrevistaIdRoute = EntrevistaIdRouteImport.update({
  id: '/entrevista/$id',
  path: '/entrevista/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVagaMatchRoute = ApiPublicVagaMatchRouteImport.update({
  id: '/api/public/vaga-match',
  path: '/api/public/vaga-match',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensaoPerfilRoute = ApiPublicExtensaoPerfilRouteImport.update({
  id: '/api/public/extensao/perfil',
  path: '/api/public/extensao/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExtensaoSalvarRoute = ApiPublicExtensaoSalvarRouteImport.update({
  id: '/api/public/extensao/salvar',
  path: '/api/public/extensao/salvar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicRadarAlertasRoute = ApiPublicRadarAlertasRouteImport.update({
  id: '/api/public/radar/alertas',
  path: '/api/public/radar/alertas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidaturas': typeof CandidaturasRoute
  '/conquistas': typeof ConquistasRoute
  '/demo': typeof DemoRoute
  '/extensao': typeof ExtensaoRoute
  '/game': typeof GameRoute
  '/guia-ats': typeof GuiaAtsRoute
  '/ia': typeof IaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/radar': typeof RadarRoute
  '/termos': typeof TermosRoute
  '/trilha': typeof TrilhaRoute
  '/a/$id': typeof AIdRoute
  '/entrevista/$id': typeof EntrevistaIdRoute
  '/api/public/vaga-match': typeof ApiPublicVagaMatchRoute
  '/api/public/extensao/perfil': typeof ApiPublicExtensaoPerfilRoute
  '/api/public/extensao/salvar': typeof ApiPublicExtensaoSalvarRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/radar/alertas': typeof ApiPublicRadarAlertasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidaturas': typeof CandidaturasRoute
  '/conquistas': typeof ConquistasRoute
  '/demo': typeof DemoRoute
  '/extensao': typeof ExtensaoRoute
  '/game': typeof GameRoute
  '/guia-ats': typeof GuiaAtsRoute
  '/ia': typeof IaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/radar': typeof RadarRoute
  '/termos': typeof TermosRoute
  '/trilha': typeof TrilhaRoute
  '/a/$id': typeof AIdRoute
  '/entrevista/$id': typeof EntrevistaIdRoute
  '/api/public/vaga-match': typeof ApiPublicVagaMatchRoute
  '/api/public/extensao/perfil': typeof ApiPublicExtensaoPerfilRoute
  '/api/public/extensao/salvar': typeof ApiPublicExtensaoSalvarRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/radar/alertas': typeof ApiPublicRadarAlertasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/candidaturas': typeof CandidaturasRoute
  '/conquistas': typeof ConquistasRoute
  '/demo': typeof DemoRoute
  '/extensao': typeof ExtensaoRoute
  '/game': typeof GameRoute
  '/guia-ats': typeof GuiaAtsRoute
  '/ia': typeof IaRoute
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/progresso': typeof ProgressoRoute
  '/radar': typeof RadarRoute
  '/termos': typeof TermosRoute
  '/trilha': typeof TrilhaRoute
  '/a/$id': typeof AIdRoute
  '/entrevista/$id': typeof EntrevistaIdRoute
  '/api/public/vaga-match': typeof ApiPublicVagaMatchRoute
  '/api/public/extensao/perfil': typeof ApiPublicExtensaoPerfilRoute
  '/api/public/extensao/salvar': typeof ApiPublicExtensaoSalvarRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/radar/alertas': typeof ApiPublicRadarAlertasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/candidaturas'
    | '/conquistas'
    | '/demo'
    | '/extensao'
    | '/game'
    | '/guia-ats'
    | '/ia'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/progresso'
    | '/radar'
    | '/termos'
    | '/trilha'
    | '/a/$id'
    | '/entrevista/$id'
    | '/api/public/vaga-match'
    | '/api/public/extensao/perfil'
    | '/api/public/extensao/salvar'
    | '/api/public/payments/webhook'
    | '/api/public/radar/alertas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/candidaturas'
    | '/conquistas'
    | '/demo'
    | '/extensao'
    | '/game'
    | '/guia-ats'
    | '/ia'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/progresso'
    | '/radar'
    | '/termos'
    | '/trilha'
    | '/a/$id'
    | '/entrevista/$id'
    | '/api/public/vaga-match'
    | '/api/public/extensao/perfil'
    | '/api/public/extensao/salvar'
    | '/api/public/payments/webhook'
    | '/api/public/radar/alertas'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/candidaturas'
    | '/conquistas'
    | '/demo'
    | '/extensao'
    | '/game'
    | '/guia-ats'
    | '/ia'
    | '/perfil'
    | '/planos'
    | '/privacidade'
    | '/progresso'
    | '/radar'
    | '/termos'
    | '/trilha'
    | '/a/$id'
    | '/entrevista/$id'
    | '/api/public/vaga-match'
    | '/api/public/extensao/perfil'
    | '/api/public/extensao/salvar'
    | '/api/public/payments/webhook'
    | '/api/public/radar/alertas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CandidaturasRoute: typeof CandidaturasRoute
  ConquistasRoute: typeof ConquistasRoute
  DemoRoute: typeof DemoRoute
  ExtensaoRoute: typeof ExtensaoRoute
  GameRoute: typeof GameRoute
  GuiaAtsRoute: typeof GuiaAtsRoute
  IaRoute: typeof IaRoute
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgressoRoute: typeof ProgressoRoute
  RadarRoute: typeof RadarRoute
  TermosRoute: typeof TermosRoute
  TrilhaRoute: typeof TrilhaRoute
  AIdRoute: typeof AIdRoute
  EntrevistaIdRoute: typeof EntrevistaIdRoute
  ApiPublicVagaMatchRoute: typeof ApiPublicVagaMatchRoute
  ApiPublicExtensaoPerfilRoute: typeof ApiPublicExtensaoPerfilRoute
  ApiPublicExtensaoSalvarRoute: typeof ApiPublicExtensaoSalvarRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicRadarAlertasRoute: typeof ApiPublicRadarAlertasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidaturas': {
      id: '/candidaturas'
      path: '/candidaturas'
      fullPath: '/candidaturas'
      preLoaderRoute: typeof CandidaturasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conquistas': {
      id: '/conquistas'
      path: '/conquistas'
      fullPath: '/conquistas'
      preLoaderRoute: typeof ConquistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensao': {
      id: '/extensao'
      path: '/extensao'
      fullPath: '/extensao'
      preLoaderRoute: typeof ExtensaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game': {
      id: '/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof GameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-ats': {
      id: '/guia-ats'
      path: '/guia-ats'
      fullPath: '/guia-ats'
      preLoaderRoute: typeof GuiaAtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/radar': {
      id: '/radar'
      path: '/radar'
      fullPath: '/radar'
      preLoaderRoute: typeof RadarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$id': {
      id: '/a/$id'
      path: '/a/$id'
      fullPath: '/a/$id'
      preLoaderRoute: typeof AIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrevista/$id': {
      id: '/entrevista/$id'
      path: '/entrevista/$id'
      fullPath: '/entrevista/$id'
      preLoaderRoute: typeof EntrevistaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vaga-match': {
      id: '/api/public/vaga-match'
      path: '/api/public/vaga-match'
      fullPath: '/api/public/vaga-match'
      preLoaderRoute: typeof ApiPublicVagaMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extensao/perfil': {
      id: '/api/public/extensao/perfil'
      path: '/api/public/extensao/perfil'
      fullPath: '/api/public/extensao/perfil'
      preLoaderRoute: typeof ApiPublicExtensaoPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/extensao/salvar': {
      id: '/api/public/extensao/salvar'
      path: '/api/public/extensao/salvar'
      fullPath: '/api/public/extensao/salvar'
      preLoaderRoute: typeof ApiPublicExtensaoSalvarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/radar/alertas': {
      id: '/api/public/radar/alertas'
      path: '/api/public/radar/alertas'
      fullPath: '/api/public/radar/alertas'
      preLoaderRoute: typeof ApiPublicRadarAlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CandidaturasRoute: CandidaturasRoute,
  ConquistasRoute: ConquistasRoute,
  DemoRoute: DemoRoute,
  ExtensaoRoute: ExtensaoRoute,
  GameRoute: GameRoute,
  GuiaAtsRoute: GuiaAtsRoute,
  IaRoute: IaRoute,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgressoRoute: ProgressoRoute,
  RadarRoute: RadarRoute,
  TermosRoute: TermosRoute,
  TrilhaRoute: TrilhaRoute,
  AIdRoute: AIdRoute,
  EntrevistaIdRoute: EntrevistaIdRoute,
  ApiPublicVagaMatchRoute: ApiPublicVagaMatchRoute,
  ApiPublicExtensaoPerfilRoute: ApiPublicExtensaoPerfilRoute,
  ApiPublicExtensaoSalvarRoute: ApiPublicExtensaoSalvarRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicRadarAlertasRoute: ApiPublicRadarAlertasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
